#! /usr/bin/env python
import os;

root = os.path.abspath(os.path.realpath(__file__)).replace('/install', '');
def createSymLink(src, dst):
	print('Creating symlink from '+src+' to '+dst);
	if (os.path.exists(dst)):
		os.remove(dst);
		
	os.symlink(src, dst);

print('Remember to run with sudo');

createSymLink(os.path.join(root, 'build.py'), '/usr/bin/ent-build');
createSymLink(os.path.join(root, 'scaffolding.py'), '/usr/bin/ent-scaffolding');
